server:
  port: 8050
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: customer
        uri: http://localhost:8090
        predicates:
        - Path=/customer/**
      - id: article
        uri: http://localhost:8060
        predicates:
        - Path=/article/**
      - id: order
        uri: http://localhost:8070
        predicates:
        - Path=/order/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/